### ISSUE TITLE
REQUEST: Integrate with tailwindui-crawler

### ISSUE THREAD

**Issue by kiliman** [vesper8/vue-tailwind-prefix-applicator#1]
Hi, I wrote a tool https://github.com/kiliman/tailwindui-crawler that downloads all the components from the tailwindui.com site (with login of course). The crawler supports a transformer pipeline where each transformer can modify the HTML code before passing on to the next one.

One of the requests on the Discord chat was to add a prefix to the components automatically. Since you've already implemented it, I'd like to add this as a transformer to my tool.

I didn't see a LICENSE in your repo, so wasn't sure if I could use your code.

Thanks for your consideration.

**Comment by vesper8** [comment]
Hey! That sounds like a really cool tool! I get the feeling that Adam will be giving us better access to the source code for Tailwind UI very soon now that Github has just launched free private Github repositories for teams a few days ago. But your tool sounds very useful especially since if it can add a prefix automatically.. this is something that I find myself doing constantly.

I've just added the MIT license and you have my permission to do with this code as you wish :)

**Comment by kiliman** [comment]
It works!

![image](https://user-images.githubusercontent.com/47168/79616436-0e9f5800-80d3-11ea-8e31-26d916e71292.png)

**Comment by connecteev** [comment]
@kiliman your tool is great! How can we make use of this functionality to add a prefix to the components automatically? I imagine this will be another transformer?

Note: as an aside, this repo has some (minor) issues like https://github.com/vesper8/vue-tailwind-prefix-applicator/issues/3 which I am hoping @vesper8 will look into. Thank you both for the amazing work and consideration.
