### ISSUE TITLE
Support for tailwind 1.4.6

### ISSUE THREAD

**Issue by connecteev** [vesper8/vue-tailwind-prefix-applicator#5]
Add support for https://github.com/tailwindcss/tailwindcss/releases/tag/v1.4.6
and capture all changes from 1.3.0 -> 1.4.6

**Comment by connecteev** [comment]
@vesper8 I hope these issues arent becoming an annoyance! Let me know if so...and thanks!

**Comment by vesper8** [comment]
@connecteev support for 1.4.4 is already included... have there really been a change in classes since 1.4.4 ? The release notes don't seem to indicate so

If the online demo does not appear to support 1.4.x, then make sure to clear the cache or use incognito as vue-cli PWAs tend to be stingy with the cache

**Comment by connecteev** [comment]
@vesper8 got it! I didnt realize 1.4.4was included..thanks!
